[package]
name = "micro_cli_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
shell_parser = { path = "../shell_parser" }

[lib]
proc-macro = true
