[app]
name = "zzhack"
terminal_window = false
mac_title_bar = true
prompt_placeholder = "Type a command and press Enter ⏎"
prompt_symbol = "❯"
routes = [
  { path = "/", command = 'clear && ls -p'},
  { path = "/posts/{*file_path}", command = 'clear && render {*file_path}'},
  { path = "/{*folder_path}", command = 'clear && render .' },
  { path = "*", command = 'clear && echo "Not found!"' }
]

[author]
name = "Mist"
email = "mist.zzh@gmail.com"
avatar = "avatar.png"
