[package]
name = "system_api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-net = { version = "0.5", default-features = false, features = ["http"] }
