name: Deploy to Netlify

on:
  push:
    branches: [main]

permissions:
  contents: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Netlify
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: jetli/trunk-action@v0.5.1
        with:
          version: 'latest'

      - name: Install Rust target
        run: rustup target add wasm32-unknown-unknown

      - name: Generate metadata
        working-directory: ./app
        run: cargo xtask metadata-generate

      - name: Build
        working-directory: ./app
        run: trunk build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './app/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AK }}
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
